---
- name: Create User based Application for {{ app_user }}
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    groups: www-data
    append: yes
    createhome: yes
    home: /srv/{{ app_user }}

- name: Change permission for user home directory
  shell: "chown -R {{ app_user }}:www-data /srv/{{ app_user }}"
  args:
    executable: /bin/bash
  become: yes
